// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Container
*/
package message

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Container struct {
	MID              *string `protobuf:"bytes,1,opt" json:"MID,omitempty"`
	SID              *string `protobuf:"bytes,2,req" json:"SID,omitempty"`
	RID              *string `protobuf:"bytes,3,req" json:"RID,omitempty"`
	TYPE             *uint32 `protobuf:"varint,4,req" json:"TYPE,omitempty"`
	STIME            *int64  `protobuf:"varint,5,req" json:"STIME,omitempty"`
	BODY             *string `protobuf:"bytes,6,req" json:"BODY,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}

func (m *Container) GetMID() string {
	if m != nil && m.MID != nil {
		return *m.MID
	}
	return ""
}

func (m *Container) GetSID() string {
	if m != nil && m.SID != nil {
		return *m.SID
	}
	return ""
}

func (m *Container) GetRID() string {
	if m != nil && m.RID != nil {
		return *m.RID
	}
	return ""
}

func (m *Container) GetTYPE() uint32 {
	if m != nil && m.TYPE != nil {
		return *m.TYPE
	}
	return 0
}

func (m *Container) GetSTIME() int64 {
	if m != nil && m.STIME != nil {
		return *m.STIME
	}
	return 0
}

func (m *Container) GetBODY() string {
	if m != nil && m.BODY != nil {
		return *m.BODY
	}
	return ""
}

func init() {
}
